package com.example.ui

import android.content.Context
import android.print.PrintAttributes
import android.print.PrintManager
import android.webkit.WebView
import android.webkit.WebViewClient
import com.example.data.VehicleInvoice

fun exportSummaryToPdf(context: Context, date: String, invoices: List<VehicleInvoice>) {
    val webView = WebView(context)
    val htmlDocument = buildHtmlSummary(date, invoices)
    
    webView.webViewClient = object : WebViewClient() {
        override fun onPageFinished(view: WebView, url: String) {
            val printManager = context.getSystemService(Context.PRINT_SERVICE) as PrintManager
            val jobName = "Ledger_Summary_${date.replace("-", "")}"
            val printAdapter = view.createPrintDocumentAdapter(jobName)
            printManager.print(jobName, printAdapter, PrintAttributes.Builder().build())
        }
    }
    
    webView.loadDataWithBaseURL(null, htmlDocument, "text/HTML", "UTF-8", null)
}

fun buildHtmlSummary(date: String, invoices: List<VehicleInvoice>): String {
    val totalGross = invoices.sumOf { it.calculateGrossRevenue() }
    val totalTransport = invoices.sumOf { it.transportCharges }
    val totalCommission = invoices.sumOf { it.calculateCommission() }
    val totalProfit = invoices.sumOf { it.calculateFinalBalance() }
    
    val rowsHtml = invoices.joinToString("\n") { 
        """
        <tr>
            <td>${it.vehicleNumber}</td>
            <td>${it.netWeight} Tons</td>
            <td>Rs ${it.calculateGrossRevenue()}</td>
            <td style="color: red;">- Rs ${it.transportCharges}</td>
            <td style="color: red;">- Rs ${it.calculateCommission()}</td>
            <td style="font-weight: bold; color: green;">Rs ${it.calculateFinalBalance()}</td>
        </tr>
        """
    }

    return """
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: sans-serif; padding: 20px; color: #333; }
                h1 { text-align: center; color: #111; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px; }
                th, td { border: 1px solid #ddd; padding: 12px 8px; text-align: left; }
                th { background-color: #f8f9fa; color: #333; }
                .summary { margin-top: 20px; background-color: #f8f9fa; padding: 20px; border-radius: 8px; border: 1px solid #ddd; }
                .summary-item { display: flex; justify-content: space-between; border-bottom: 1px solid #eee; padding: 8px 0; font-size: 16px; }
                .summary-item:last-child { border-bottom: none; }
                .profit { color: #2e7d32; font-size: 20px; font-weight: bold; margin-top: 10px; }
            </style>
        </head>
        <body>
            <h1>LogiLedger Summary: $date</h1>
            <div class="summary">
                <div class="summary-item"><span>Total Vehicles Handled:</span> <b>${invoices.size}</b></div>
                <div class="summary-item"><span>Cumulative Gross Sums:</span> <b>Rs $totalGross</b></div>
                <div class="summary-item"><span>Cumulative Transport Deductions:</span> <b style="color: red;">- Rs $totalTransport</b></div>
                <div class="summary-item"><span>Cumulative Commissions Charge:</span> <b style="color: red;">- Rs $totalCommission</b></div>
                <div class="summary-item profit"><span>FINAL NET PROFIT:</span> <span>Rs $totalProfit</span></div>
            </div>
            
            <h2 style="margin-top: 30px;">Vehicle Breakdowns</h2>
            <table>
                <tr>
                    <th>Vehicle ID</th>
                    <th>Net Weight</th>
                    <th>Gross</th>
                    <th>Transport</th>
                    <th>Commission</th>
                    <th>Net Profit</th>
                </tr>
                $rowsHtml
            </table>
            
            <div style="margin-top: 50px; text-align: center; color: #888; font-size: 12px;">
                Generated by LogiLedger Application
            </div>
        </body>
        </html>
    """.trimIndent()
}
